import { useState, useEffect, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { Download, Printer, Truck, ArrowRight, FileText, Clock, ClipboardCheck, Filter, ChevronLeft, ChevronRight, Plus, Edit2, Trash2, X, AlertTriangle, Eye } from "lucide-react";
import toast from "react-hot-toast";
import Breadcrumb from "@/components/common/Breadcrumb";
import { managerApi } from "../api/managerApi";

const TABS = ["All Bills", "Active", "Expiring Soon", "Expired"];

// Subcomponent for E-Way Bill View Dialog (Includes high-quality canvas preview)
function EWayBillViewModal({ bill, onClose }) {
  const canvasRef = useRef(null);

  useEffect(() => {
    if (!bill || !canvasRef.current) return;
    const canvas = canvasRef.current;
    const ctx = canvas.getContext("2d");

    // Clear canvas
    ctx.clearRect(0, 0, 800, 1000);

    // Background
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, 800, 1000);

    // Thick outer border
    ctx.strokeStyle = "#1e293b";
    ctx.lineWidth = 5;
    ctx.strokeRect(20, 20, 760, 960);

    // Double thin header border
    ctx.strokeStyle = "#1e293b";
    ctx.lineWidth = 1;
    ctx.strokeRect(25, 25, 750, 950);

    // Header Content
    ctx.fillStyle = "#1e293b";
    ctx.font = "bold 26px Arial, Helvetica, sans-serif";
    ctx.textAlign = "center";
    ctx.fillText("GST E-WAY BILL SYSTEM", 400, 75);
    ctx.font = "14px Arial, Helvetica, sans-serif";
    ctx.fillText("GOVERNMENT OF INDIA", 400, 100);

    // Horizontal divider
    ctx.strokeStyle = "#475569";
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(25, 120);
    ctx.lineTo(775, 120);
    ctx.stroke();

    const ewbNumber = bill.ewayBillNo || "";
    const genDate = new Date(bill.createdAt).toLocaleDateString("en-IN", {
      day: "2-digit",
      month: "2-digit",
      year: "numeric"
    }) + " " + new Date(bill.createdAt).toLocaleTimeString("en-IN", {
      hour: "2-digit",
      minute: "2-digit"
    });

    // Bill Number and Date Details
    ctx.textAlign = "left";
    ctx.fillStyle = "#0f172a";
    ctx.font = "bold 15px Arial, Helvetica, sans-serif";
    ctx.fillText(`E-WAY BILL NO:  ${ewbNumber}`, 50, 160);
    ctx.fillText(`GENERATION DATE: ${genDate}`, 50, 185);
    ctx.font = "13px Arial, Helvetica, sans-serif";
    ctx.fillStyle = "#475569";
    ctx.fillText(`GENERATED BY:   GSTIN-27AAAAA1111A1Z1 (Alex Thompson)`, 50, 210);

    // Barcode mock
    ctx.fillStyle = "#000000";
    for (let i = 0; i < 48; i++) {
      let width = i % 3 === 0 ? 5 : i % 2 === 0 ? 2 : 3;
      ctx.fillRect(480 + i * 5, 140, width, 55);
    }
    ctx.font = "10px monospace";
    ctx.textAlign = "center";
    ctx.fillText(ewbNumber.replace(/\s+/g, ""), 600, 210);

    // Horizontal divider
    ctx.strokeStyle = "#94a3b8";
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(25, 230);
    ctx.lineTo(775, 230);
    ctx.stroke();

    // PART-A Block
    ctx.fillStyle = "#1e293b";
    ctx.fillRect(50, 250, 700, 30);
    ctx.fillStyle = "#ffffff";
    ctx.font = "bold 13px Arial, Helvetica, sans-serif";
    ctx.textAlign = "left";
    ctx.fillText("PART-A (Document & Address Details)", 65, 270);

    ctx.fillStyle = "#0f172a";
    ctx.font = "14px Arial, Helvetica, sans-serif";
    
    const partALabels = [
      `1. GSTIN of Supplier:    27BBBBB2222B2Z2 (Fleet Corp Ltd)`,
      `2. GSTIN of Recipient:   29CCCCC3333C3Z3 (Client Logistics Ltd)`,
      `3. Place of Dispatch:    ${bill.fromLoc}`,
      `4. Place of Delivery:    ${bill.toLoc}`,
      `5. Document No & Date:   ${bill.invoiceNo} / ${genDate.split(" ")[0]}`,
      `6. Value of Goods:       ${bill.goodsValue}`,
      `7. HSN Code / Category:  8708 / Automobile Spares`
    ];

    partALabels.forEach((label, idx) => {
      ctx.fillText(label, 70, 315 + idx * 32);
    });

    // PART-B Block
    ctx.fillStyle = "#1e293b";
    ctx.fillRect(50, 560, 700, 30);
    ctx.fillStyle = "#ffffff";
    ctx.font = "bold 13px Arial, Helvetica, sans-serif";
    ctx.fillText("PART-B (Vehicle & Transporter Details)", 65, 580);

    ctx.fillStyle = "#0f172a";
    ctx.font = "14px Arial, Helvetica, sans-serif";
    
    const partBLabels = [
      `1. Transporter Name:     ${bill.transporterName}`,
      `2. Vehicle Number:       ${bill.vehicleNo.toUpperCase()}`,
      `3. Mode of Transport:    Road`,
      `4. Multi-Vehicle Option: No (Direct Transit)`
    ];

    partBLabels.forEach((label, idx) => {
      ctx.fillText(label, 70, 625 + idx * 32);
    });

    // Outer box for Parts
    ctx.strokeStyle = "#cbd5e1";
    ctx.lineWidth = 1;
    ctx.strokeRect(50, 250, 700, 510);

    // Official verification seal
    ctx.strokeStyle = "#059669";
    ctx.lineWidth = 3;
    ctx.strokeRect(530, 800, 200, 90);
    
    ctx.fillStyle = "#059669";
    ctx.font = "bold 13px Arial, Helvetica, sans-serif";
    ctx.textAlign = "center";
    ctx.fillText("GST DEPARTMENT", 630, 825);
    ctx.font = "bold 12px Arial, Helvetica, sans-serif";
    ctx.fillText("VERIFIED & APPROVED", 630, 850);
    ctx.font = "9px Arial, Helvetica, sans-serif";
    ctx.fillText("E-WAY BILL COMPLIANCE", 630, 875);

    // QR Code Mock
    ctx.fillStyle = "#1e293b";
    ctx.fillRect(70, 800, 100, 100);
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(78, 808, 84, 84);
    ctx.fillStyle = "#1e293b";
    ctx.fillRect(84, 814, 25, 25);
    ctx.fillRect(129, 814, 25, 25);
    ctx.fillRect(84, 859, 25, 25);
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(89, 819, 15, 15);
    ctx.fillRect(134, 819, 15, 15);
    ctx.fillRect(89, 864, 15, 15);
    ctx.fillStyle = "#1e293b";
    ctx.fillRect(94, 824, 5, 5);
    ctx.fillRect(139, 824, 5, 5);
    ctx.fillRect(94, 869, 5, 5);
    ctx.fillRect(115, 825, 6, 6);
    ctx.fillRect(125, 845, 8, 4);
    ctx.fillRect(110, 860, 4, 12);
    ctx.fillRect(135, 860, 12, 12);

    // Footer note
    ctx.fillStyle = "#64748b";
    ctx.font = "12px Arial, Helvetica, sans-serif";
    ctx.textAlign = "center";
    ctx.fillText("This is an electronically generated compliance receipt. No physical signature is required.", 400, 940);
    ctx.fillText("Validity subject to standard transit authority checks on the GST portal.", 400, 960);
  }, [bill]);

  const handleDownloadImage = () => {
    if (!canvasRef.current) return;
    const canvas = canvasRef.current;
    const url = canvas.toDataURL("image/png");
    const link = document.createElement("a");
    link.href = url;
    link.download = `EWayBill_${bill.ewayBillNo.replace(/\s+/g, "_")}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    toast.success("E-Way Bill image downloaded!");
  };

  return (
    <div className="fixed inset-0 bg-black/45 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl border border-gray-100 w-full max-w-4xl p-6 shadow-2xl animate-in fade-in zoom-in-95 duration-150 flex flex-col md:flex-row gap-6 max-h-[90vh] overflow-y-auto relative">
        {/* Left Column: Details */}
        <div className="flex-1 flex flex-col justify-between">
          <div>
            <div className="flex justify-between items-center mb-6">
              <div>
                <h3 className="text-xl font-bold text-gray-800 font-poppins">E-Way Bill Details</h3>
                <p className="text-xs text-gray-500 font-nunito mt-0.5">Verification & status overview</p>
              </div>
              <button 
                onClick={onClose} 
                className="p-1.5 hover:bg-gray-100 rounded-lg transition-colors cursor-pointer md:hidden"
              >
                <X className="w-4 h-4 text-gray-500" />
              </button>
            </div>

            <div className="space-y-4 font-nunito text-xs text-gray-750">
              <div className="grid grid-cols-2 gap-4 bg-slate-50 p-4 rounded-xl border border-slate-100">
                <div>
                  <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">E-Way Bill No</span>
                  <strong className="text-gray-900 text-sm">{bill.ewayBillNo}</strong>
                </div>
                <div>
                  <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">Status</span>
                  <span className={`px-2 py-0.5 rounded text-[9px] font-black inline-block uppercase mt-1 text-white ${
                    bill.status === "Active" 
                      ? "bg-green-600" 
                      : bill.status === "Expiring Soon" 
                        ? "bg-amber-600" 
                        : bill.status === "Expires Today"
                          ? "bg-blue-600"
                          : "bg-red-600"
                  }`}>
                    {bill.status}
                  </span>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <span className="text-[10px] font-bold text-gray-450 uppercase tracking-wider block">Vehicle Number</span>
                  <span className="font-bold text-gray-900 uppercase">{bill.vehicleNo}</span>
                </div>
                <div>
                  <span className="text-[10px] font-bold text-gray-450 uppercase tracking-wider block">Transporter</span>
                  <span className="font-semibold text-gray-900">{bill.transporterName}</span>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <span className="text-[10px] font-bold text-gray-450 uppercase tracking-wider block">From Location</span>
                  <span className="font-semibold text-gray-900">{bill.fromLoc}</span>
                </div>
                <div>
                  <span className="text-[10px] font-bold text-gray-450 uppercase tracking-wider block">To Location</span>
                  <span className="font-semibold text-gray-900">{bill.toLoc}</span>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <span className="text-[10px] font-bold text-gray-450 uppercase tracking-wider block">Invoice No</span>
                  <span className="font-bold text-gray-900">{bill.invoiceNo}</span>
                </div>
                <div>
                  <span className="text-[10px] font-bold text-gray-450 uppercase tracking-wider block">Goods Value</span>
                  <span className="font-bold text-gray-900">₹{parseFloat(bill.goodsValue || "0").toLocaleString("en-IN")}</span>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <span className="text-[10px] font-bold text-gray-455 uppercase tracking-wider block">Validity (Until)</span>
                  <span className="font-semibold text-gray-900">{bill.validity}</span>
                </div>
                <div>
                  <span className="text-[10px] font-bold text-gray-455 uppercase tracking-wider block">Remaining Validity</span>
                  <span className="font-extrabold text-[#1E293B]">{bill.remainingValidityText}</span>
                </div>
              </div>
            </div>
          </div>

          <div className="flex gap-3 mt-8 pt-4 border-t border-gray-100">
            <button
              onClick={onClose}
              className="px-4 py-2 border border-gray-250 rounded-xl text-xs font-bold text-gray-600 hover:bg-gray-50 cursor-pointer active:scale-95 transition-all flex-1 md:flex-none"
            >
              Close
            </button>
            <button
              onClick={handleDownloadImage}
              className="px-4 py-2 bg-amber-700 hover:bg-amber-800 text-white rounded-xl text-xs font-bold shadow-md shadow-amber-700/10 cursor-pointer active:scale-95 transition-all flex items-center justify-center gap-1.5 flex-1 md:flex-none"
            >
              <Download className="w-3.5 h-3.5" />
              Download Receipt
            </button>
          </div>
        </div>

        {/* Right Column: Canvas Receipt Image Preview */}
        <div className="w-full md:w-[400px] flex flex-col items-center border border-gray-200 rounded-xl p-2 bg-gray-50 shrink-0">
          <div className="w-full text-center py-2 border-b border-gray-200 mb-2">
            <span className="text-[10px] font-black text-gray-400 uppercase tracking-widest font-poppins">Compliance Document Preview</span>
          </div>
          <div className="w-full overflow-auto max-h-[50vh] md:max-h-[60vh] border border-gray-200 rounded-lg shadow-inner bg-white flex justify-center">
            <canvas 
              ref={canvasRef} 
              width={800} 
              height={1000} 
              className="w-[350px] h-[437.5px]"
            />
          </div>
        </div>
        
        {/* Close button top right (hidden on mobile, close is at bottom) */}
        <button 
          onClick={onClose} 
          className="absolute top-4 right-4 p-2 bg-white/80 hover:bg-gray-100 rounded-xl border border-gray-200 transition-all cursor-pointer shadow-sm hidden md:flex"
        >
          <X className="w-4 h-4 text-gray-500" />
        </button>
      </div>
    </div>
  );
}

const parseValidityToLocalDatetime = (validityStr) => {
  if (!validityStr) return "";
  
  const now = new Date();
  let targetDate = new Date();

  try {
    const cleanStr = validityStr.toLowerCase().trim();
    if (cleanStr.includes("today")) {
      const timePart = cleanStr.split(",")[1]?.trim() || "";
      const [h, m] = timePart.split(":").map(Number);
      if (!isNaN(h) && !isNaN(m)) {
        targetDate.setHours(h, m, 0, 0);
      }
    } else if (cleanStr.includes("awaiting")) {
      targetDate.setDate(targetDate.getDate() + 1);
    } else {
      const parts = cleanStr.split(",");
      const datePart = parts[0]?.trim();
      const timePart = parts[1]?.trim();
      
      if (datePart) {
        const dateTokens = datePart.split(/\s+/);
        const day = parseInt(dateTokens[0]);
        const monthStr = dateTokens[1];
        
        const monthNames = ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"];
        const monthIdx = monthNames.indexOf(monthStr?.substring(0, 3));
        
        if (!isNaN(day) && monthIdx !== -1) {
          targetDate.setDate(day);
          targetDate.setMonth(monthIdx);
          targetDate.setFullYear(2026);
        }
      }
      
      if (timePart) {
        const [h, m] = timePart.split(":").map(Number);
        if (!isNaN(h) && !isNaN(m)) {
          targetDate.setHours(h, m, 0, 0);
        }
      }
    }
  } catch (err) {
    console.error("Error parsing validity date:", err);
  }

  const year = targetDate.getFullYear();
  const month = String(targetDate.getMonth() + 1).padStart(2, '0');
  const day = String(targetDate.getDate()).padStart(2, '0');
  const hours = String(targetDate.getHours()).padStart(2, '0');
  const minutes = String(targetDate.getMinutes()).padStart(2, '0');
  
  return `${year}-${month}-${day}T${hours}:${minutes}`;
};

const formatLocalDatetimeToValidity = (dateTimeStr) => {
  if (!dateTimeStr) return "Awaiting Sync";
  try {
    const d = new Date(dateTimeStr);
    if (isNaN(d.getTime())) return "Awaiting Sync";
    
    return d.toLocaleDateString("en-IN", {
      day: "2-digit",
      month: "short"
    }) + ", " + d.toLocaleTimeString("en-IN", {
      hour: "2-digit",
      minute: "2-digit",
      hour12: false
    });
  } catch (err) {
    return "Awaiting Sync";
  }
};

export default function EWayBillsPage() {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState("All Bills");
  const [searchQuery, setSearchQuery] = useState("");
  const [bills, setBills] = useState([]);
  const [loading, setLoading] = useState(true);

  // Modal States
  const [selectedBill, setSelectedBill] = useState(null);
  const [viewModalOpen, setViewModalOpen] = useState(false);
  const [editModalOpen, setEditModalOpen] = useState(false);
  const [deleteModalOpen, setDeleteModalOpen] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);
  const [editFormData, setEditFormData] = useState({
    vehicleNo: "",
    transporterName: "",
    fromLoc: "",
    toLoc: "",
    invoiceNo: "",
    goodsValue: "",
    validity: ""
  });

  const fetchBills = async () => {
    try {
      setLoading(true);
      const res = await managerApi.getEWayBills();
      const data = res.data?.data || res.data || [];
      setBills(data);
    } catch (err) {
      toast.error("Failed to fetch E-Way Bills");
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchBills();
  }, []);

  const filteredBills = bills.filter((b) => {
    // Tab filter
    let tabMatch = true;
    if (activeTab === "Active") tabMatch = b.status === "Active" || b.status === "Expires Today";
    else if (activeTab === "Expiring Soon") tabMatch = b.status === "Expiring Soon";
    else if (activeTab === "Expired") tabMatch = b.status === "Expired";
    
    if (!tabMatch) return false;
    
    // Search filter (fuzzy, case-insensitive)
    if (searchQuery.trim() !== "") {
      const query = searchQuery.toLowerCase().trim();
      const billNo = (b.ewayBillNo || "").toLowerCase();
      const vehNo = (b.vehicleNo || "").toLowerCase();
      const customer = (b.transporterName || "").toLowerCase();
      return billNo.includes(query) || vehNo.includes(query) || customer.includes(query);
    }
    
    return true;
  });

  const handleDownload = () => toast.success("Downloading E-Way Bills...");
  const handlePrint = () => toast.success("Sending to printer...");
  
  const handleExtend = async (id, ewbNo) => {
    try {
      await managerApi.extendEWayBill(id);
      toast.success(`Extended validity for ${ewbNo}`);
      fetchBills();
    } catch (err) {
      toast.error("Failed to extend E-Way Bill validity");
      console.error(err);
    }
  };

  const handleViewClick = (bill) => {
    setSelectedBill(bill);
    setViewModalOpen(true);
  };

  const handleEditClick = (bill) => {
    setSelectedBill(bill);
    setEditFormData({
      vehicleNo: bill.vehicleNo || "",
      transporterName: bill.transporterName || "",
      fromLoc: bill.fromLoc || "",
      toLoc: bill.toLoc || "",
      invoiceNo: bill.invoiceNo || "",
      goodsValue: bill.goodsValue || "",
      validity: parseValidityToLocalDatetime(bill.validity)
    });
    setEditModalOpen(true);
  };

  const handleEditSubmit = async (e) => {
    e.preventDefault();
    try {
      setIsSaving(true);
      const payload = {
        ...editFormData,
        validity: formatLocalDatetimeToValidity(editFormData.validity)
      };
      await managerApi.updateEWayBill(selectedBill._id, payload);
      toast.success("E-Way Bill updated successfully!");
      setEditModalOpen(false);
      setSelectedBill(null);
      fetchBills();
    } catch (err) {
      toast.error(err.response?.data?.message || err.message || "Failed to update E-Way Bill");
      console.error(err);
    } finally {
      setIsSaving(false);
    }
  };

  const handleDeleteClick = (bill) => {
    setSelectedBill(bill);
    setDeleteModalOpen(true);
  };

  const handleDeleteConfirm = async () => {
    try {
      setIsDeleting(true);
      await managerApi.deleteEWayBill(selectedBill._id);
      toast.success("E-Way Bill deleted successfully!");
      setDeleteModalOpen(false);
      setSelectedBill(null);
      fetchBills();
    } catch (err) {
      toast.error(err.response?.data?.message || err.message || "Failed to delete E-Way Bill");
      console.error(err);
    } finally {
      setIsDeleting(false);
    }
  };

  const handleGenerate = () => navigate("/manager/eway/generate");

  // Dynamic KPI Stats
  const activeCount = bills.filter(b => b.status === "Active" || b.status === "Expires Today").length;
  const expiringCount = bills.filter(b => b.status === "Expiring Soon").length;
  const expiredCount = bills.filter(b => b.status === "Expired").length;

  return (
    <div className="p-8 bg-gray-50/50 min-h-screen font-poppins relative">
      <Breadcrumb />
      
      {/* Top Header Row with Actions */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8">
        <div>
          <h1 className="font-poppins font-bold text-[32px] text-[#1E293B] leading-none">E-Way Bills</h1>
          <p className="text-[18px] text-[#64748B] mt-[12px] font-medium font-nunito">
            Manage GST E-Way Bills and validity extensions for dispatches.
          </p>
        </div>
        <button
          onClick={handleGenerate}
          className="flex items-center gap-2 px-6 py-3 bg-amber-700 text-white rounded-xl font-bold hover:bg-amber-800 transition-all shadow-md shadow-amber-700/20 active:scale-95 cursor-pointer text-xs uppercase tracking-wider"
        >
          <Plus className="w-4 h-4" />
          Generate New
        </button>
      </div>

      {/* Warning/Attention notification banner */}
      {(expiringCount > 0 || expiredCount > 0) && (
        <div className="mb-8 bg-amber-50 border border-amber-200 rounded-2xl p-4 flex items-start gap-3 text-amber-800 animate-in fade-in slide-in-from-top-4 duration-300">
          <AlertTriangle className="w-5 h-5 text-amber-700 shrink-0 mt-0.5" />
          <div className="text-xs font-nunito">
            <h4 className="font-bold text-amber-900">E-Way Bills Attention Required</h4>
            <p className="mt-1 text-amber-700 font-medium">
              You have {expiringCount > 0 ? `${expiringCount} bill(s) expiring soon` : ""}
              {expiringCount > 0 && expiredCount > 0 ? " and " : ""}
              {expiredCount > 0 ? `${expiredCount} bill(s) expired` : ""}.
              Please review validity and extend dispatches as necessary.
            </p>
          </div>
        </div>
      )}

      {/* KPI Stats Row */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8 select-none">
        {/* Stat 1: Active Bills */}
        <div className="bg-white rounded-2xl border border-gray-200 p-6 shadow-sm flex flex-col justify-between border-l-4 border-l-gray-900">
          <div className="flex items-start justify-between">
            <div>
              <span className="text-xs font-bold text-gray-500 tracking-wider uppercase">Active Bills</span>
              <h3 className="text-2xl font-extrabold text-gray-800 mt-2">{activeCount}</h3>
            </div>
            <div className="bg-slate-100 text-slate-800 p-3 rounded-xl">
              <FileText className="w-5 h-5" />
            </div>
          </div>
          <div className="mt-4 text-xs text-green-600 font-semibold flex items-center gap-1">
            <span>+12% vs last month</span>
          </div>
        </div>

        {/* Stat 2: Expiring Soon */}
        <div className="bg-white rounded-2xl border border-gray-200 p-6 shadow-sm flex flex-col justify-between border-l-4 border-l-amber-600">
          <div className="flex items-start justify-between">
            <div>
              <span className="text-xs font-bold text-gray-500 tracking-wider uppercase">Expiring Soon</span>
              <h3 className="text-2xl font-extrabold text-gray-800 mt-2">{expiringCount}</h3>
            </div>
            <div className="bg-amber-50 text-amber-700 p-3 rounded-xl">
              <Clock className="w-5 h-5" />
            </div>
          </div>
          <div className="mt-4 text-xs text-red-500 font-semibold">
            Action required
          </div>
        </div>

        {/* Stat 3: Expired Bills */}
        <div className="bg-white rounded-2xl border border-gray-200 p-6 shadow-sm flex flex-col justify-between border-l-4 border-l-red-600">
          <div className="flex items-start justify-between">
            <div>
              <span className="text-xs font-bold text-gray-500 tracking-wider uppercase">Expired Bills</span>
              <h3 className="text-2xl font-extrabold text-gray-800 mt-2">{expiredCount}</h3>
            </div>
            <div className="bg-red-50 text-red-700 p-3 rounded-xl">
              <ClipboardCheck className="w-5 h-5" />
            </div>
          </div>
          <div className="mt-4 text-xs text-red-500 font-semibold">
            Action required
          </div>
        </div>
      </div>

      {/* Main Table Block */}
      <div className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden flex flex-col">
        {/* Table Filter Action bar */}
        <div className="p-4 border-b border-gray-200 flex items-center justify-between gap-4 flex-wrap bg-white">
          <div className="flex items-center gap-3 w-full sm:w-auto">
            <div className="relative w-full sm:w-64">
              <input
                type="text"
                placeholder="Search Bill, Vehicle, Customer..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-8 pr-3 py-2 border border-gray-200 rounded-xl text-xs focus:outline-none focus:border-amber-700 bg-white font-nunito"
              />
              <Filter className="w-3.5 h-3.5 text-gray-400 absolute left-2.5 top-1/2 -translate-y-1/2" />
            </div>
            <div className="flex items-center gap-1.5 overflow-x-auto no-scrollbar">
              {TABS.map((tab) => (
                <button
                  key={tab}
                  onClick={() => setActiveTab(tab)}
                  className={`px-4 py-2 rounded-xl text-xs font-bold transition-all cursor-pointer whitespace-nowrap ${
                    activeTab === tab ? "bg-black text-white shadow-sm" : "text-gray-500 hover:text-gray-800 hover:bg-gray-50"
                  }`}
                >
                  {tab}
                </button>
              ))}
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button 
              onClick={handleDownload}
              className="p-2 border border-gray-200 rounded-xl text-gray-600 hover:bg-gray-50 active:scale-95 transition-all cursor-pointer inline-flex"
              title="Download Report"
            >
              <Download className="w-4 h-4" />
            </button>
            <button 
              onClick={handlePrint}
              className="p-2 border border-gray-200 rounded-xl text-gray-600 hover:bg-gray-50 active:scale-95 transition-all cursor-pointer inline-flex"
              title="Print Document"
            >
              <Printer className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Responsive Table */}
        <div className="overflow-x-auto no-scrollbar">
          <table className="w-full text-left border-collapse text-sm font-nunito">
            <thead>
              <tr className="bg-[#F5F7FB] border-b border-[#E7EAF0] text-[#64748B] font-poppins font-semibold uppercase text-[10px] tracking-wider select-none whitespace-nowrap">
                <th className="py-4 px-6 text-left whitespace-nowrap">Bill Details</th>
                <th className="py-4 px-6 text-left whitespace-nowrap">Vehicle/Transporter</th>
                <th className="py-4 px-6 text-left whitespace-nowrap">Route</th>
                <th className="py-4 px-6 text-left whitespace-nowrap">Status</th>
                <th className="py-4 px-6 text-left whitespace-nowrap">Validity</th>
                <th className="py-4 px-6 text-right whitespace-nowrap pr-8">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#E7EAF0]/60">
              {loading ? (
                <tr>
                  <td colSpan={6} className="py-12 text-center text-gray-400 font-medium">
                    <div className="flex items-center justify-center gap-2">
                      <div className="w-4 h-4 border-2 border-amber-700 border-t-transparent rounded-full animate-spin" />
                      <span>Loading E-Way Bills...</span>
                    </div>
                  </td>
                </tr>
              ) : filteredBills.length === 0 ? (
                <tr>
                  <td colSpan={6} className="py-12 text-center text-gray-400 font-medium">
                    No E-Way Bills found.
                  </td>
                </tr>
              ) : (
                filteredBills.map((bill) => (
                  <tr key={bill._id} className="hover:bg-[#F5F7FB]/50 transition-colors">
                    {/* Bill details */}
                    <td className="py-4 px-6 whitespace-nowrap">
                      <p className="font-extrabold text-[#1E293B] text-sm">{bill.ewayBillNo}</p>
                      <span className="text-xs text-[#64748B] font-medium block mt-0.5">
                        {bill.invoiceNo?.startsWith("Tax Invoice") ? bill.invoiceNo : `Tax Invoice: ${bill.invoiceNo}`}
                      </span>
                      <span className="text-[10px] text-gray-400 font-bold block mt-1">
                        Gen: {new Date(bill.generationDate || bill.createdAt).toLocaleDateString("en-IN", { day: '2-digit', month: 'short', year: 'numeric' })}
                      </span>
                    </td>
                    
                    {/* Vehicle/Transporter */}
                    <td className="py-4 px-6 whitespace-nowrap">
                      <div className="flex items-center gap-3">
                        <div className="w-9 h-9 bg-blue-50 text-blue-600 rounded-xl flex items-center justify-center shrink-0">
                          <Truck className="w-4 h-4" />
                        </div>
                        <div>
                          <p className="font-bold text-[#1E293B] text-xs uppercase">{bill.vehicleNo}</p>
                          <span className="text-[10px] text-gray-500 font-semibold block mt-0.5">{bill.transporterName}</span>
                        </div>
                      </div>
                    </td>

                    {/* Route */}
                    <td className="py-4 px-6 whitespace-nowrap">
                      <div className="flex items-center gap-1.5 text-xs font-bold text-[#1E293B]">
                        <span>{bill.fromLoc}</span>
                        <ArrowRight className="w-3 h-3 text-[#64748B]" />
                        <span>{bill.toLoc}</span>
                      </div>
                    </td>

                    {/* Status */}
                    <td className="py-4 px-6 whitespace-nowrap">
                      <span className={`px-3 py-1 rounded-lg text-[9px] font-black inline-block uppercase tracking-wider select-none text-white ${
                        bill.status === "Active" 
                          ? "bg-green-600" 
                          : bill.status === "Expiring Soon" 
                            ? "bg-amber-600" 
                            : bill.status === "Expires Today"
                              ? "bg-blue-600"
                              : "bg-red-600"
                      }`}>
                        {bill.status}
                      </span>
                    </td>

                    {/* Validity */}
                    <td className="py-4 px-6 whitespace-nowrap">
                      <p className="text-[#1E293B] text-xs font-bold">Until: {bill.validity}</p>
                      <p className="text-[10px] font-semibold text-slate-500 mt-0.5">{bill.remainingValidityText}</p>
                      {bill.validityProgress !== null && bill.validityProgress !== undefined ? (
                        <div className="w-24 bg-gray-100 rounded-full h-1.5 mt-1.5 overflow-hidden">
                          <div 
                            className={`h-full ${bill.progressColor || "bg-[#B45A0A]"}`}
                            style={{ width: `${bill.validityProgress}%` }}
                          />
                        </div>
                      ) : (
                        <span className="flex items-center gap-0.5 mt-1 select-none">
                          <span className="w-1.5 h-1.5 rounded-full bg-slate-900 animate-bounce" style={{ animationDelay: "0ms" }} />
                          <span className="w-1.5 h-1.5 rounded-full bg-slate-900 animate-bounce" style={{ animationDelay: "150ms" }} />
                          <span className="w-1.5 h-1.5 rounded-full bg-slate-900 animate-bounce" style={{ animationDelay: "300ms" }} />
                        </span>
                      )}
                    </td>

                    {/* Actions */}
                    <td className="py-4 px-6 text-right whitespace-nowrap pr-8">
                      <div className="flex items-center justify-end gap-2">
                        {bill.canExtend && (
                          <button
                            onClick={() => handleEditClick(bill)}
                            className="px-2.5 py-1 bg-amber-700 hover:bg-amber-800 text-white rounded-lg text-[10px] font-bold uppercase tracking-wider transition-colors cursor-pointer active:scale-95 animate-pulse"
                          >
                            Extend
                          </button>
                        )}
                        <button
                          onClick={() => handleViewClick(bill)}
                          className="p-1.5 text-blue-600 bg-blue-50 hover:bg-blue-100 rounded-lg active:scale-95 transition-all cursor-pointer inline-flex"
                          title="View"
                        >
                          <Eye className="w-3.5 h-3.5" />
                        </button>
                        <button
                          onClick={() => handleEditClick(bill)}
                          className="p-1.5 text-amber-700 bg-amber-50 hover:bg-amber-100 rounded-lg active:scale-95 transition-all cursor-pointer inline-flex"
                          title="Edit"
                        >
                          <Edit2 className="w-3.5 h-3.5" />
                        </button>
                        <button
                          onClick={() => handleDeleteClick(bill)}
                          className="p-1.5 text-red-600 bg-red-50 hover:bg-red-100 rounded-lg active:scale-95 transition-all cursor-pointer inline-flex"
                          title="Delete"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-[#E7EAF0] flex items-center justify-between bg-white select-none">
          <span className="text-xs text-[#64748B] font-medium font-poppins">
            Showing 1–{filteredBills.length} of {filteredBills.length} results
          </span>
          <div className="flex items-center gap-1.5">
            <button className="w-7 h-7 flex items-center justify-center border border-[#E7EAF0] rounded bg-white text-[#64748B] hover:bg-gray-50 text-xs font-bold cursor-pointer">
              <ChevronLeft className="w-3.5 h-3.5" />
            </button>
            <button className="w-7 h-7 flex items-center justify-center border border-[#E7EAF0] rounded bg-white text-[#64748B] hover:bg-gray-50 text-xs font-bold cursor-pointer">
              <ChevronRight className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
      </div>

      {/* View E-Way Bill Modal (Includes dynamic Canvas Preview) */}
      {viewModalOpen && selectedBill && (
        <EWayBillViewModal 
          bill={selectedBill} 
          onClose={() => { setViewModalOpen(false); setSelectedBill(null); }} 
        />
      )}

      {/* Edit E-Way Bill Modal */}
      {editModalOpen && (
        <div className="fixed inset-0 bg-black/40 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl border border-gray-100 w-full max-w-lg p-6 shadow-2xl animate-in fade-in zoom-in-95 duration-150">
            <div className="flex justify-between items-center mb-6">
              <h3 className="text-lg font-bold text-gray-800 font-poppins">Edit E-Way Bill Details</h3>
              <button 
                onClick={() => { setEditModalOpen(false); setSelectedBill(null); }} 
                className="p-1.5 hover:bg-gray-100 rounded-lg transition-colors cursor-pointer"
              >
                <X className="w-4 h-4 text-gray-500" />
              </button>
            </div>
            
            <form onSubmit={handleEditSubmit} className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-gray-500 uppercase tracking-wider block">Vehicle Number</label>
                  <input
                    type="text"
                    required
                    value={editFormData.vehicleNo}
                    onChange={(e) => setEditFormData({ ...editFormData, vehicleNo: e.target.value })}
                    className="w-full p-2.5 border border-gray-200 rounded-xl text-xs focus:outline-none focus:border-amber-700 bg-white font-nunito uppercase"
                  />
                </div>
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-gray-500 uppercase tracking-wider block">Transporter Name</label>
                  <input
                    type="text"
                    required
                    value={editFormData.transporterName}
                    onChange={(e) => setEditFormData({ ...editFormData, transporterName: e.target.value })}
                    className="w-full p-2.5 border border-gray-200 rounded-xl text-xs focus:outline-none focus:border-amber-700 bg-white font-nunito"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-gray-500 uppercase tracking-wider block">From Location</label>
                  <input
                    type="text"
                    required
                    value={editFormData.fromLoc}
                    onChange={(e) => setEditFormData({ ...editFormData, fromLoc: e.target.value })}
                    className="w-full p-2.5 border border-gray-200 rounded-xl text-xs focus:outline-none focus:border-amber-700 bg-white font-nunito"
                  />
                </div>
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-gray-500 uppercase tracking-wider block">To Location</label>
                  <input
                    type="text"
                    required
                    value={editFormData.toLoc}
                    onChange={(e) => setEditFormData({ ...editFormData, toLoc: e.target.value })}
                    className="w-full p-2.5 border border-gray-200 rounded-xl text-xs focus:outline-none focus:border-amber-700 bg-white font-nunito"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-gray-500 uppercase tracking-wider block">Invoice No</label>
                  <input
                    type="text"
                    required
                    value={editFormData.invoiceNo}
                    onChange={(e) => setEditFormData({ ...editFormData, invoiceNo: e.target.value })}
                    className="w-full p-2.5 border border-gray-200 rounded-xl text-xs focus:outline-none focus:border-amber-700 bg-white font-nunito"
                  />
                </div>
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-gray-500 uppercase tracking-wider block">Goods Value</label>
                  <input
                    type="text"
                    required
                    value={editFormData.goodsValue}
                    onChange={(e) => setEditFormData({ ...editFormData, goodsValue: e.target.value })}
                    className="w-full p-2.5 border border-gray-200 rounded-xl text-xs focus:outline-none focus:border-amber-700 bg-white font-nunito"
                  />
                </div>
              </div>

              <div className="space-y-1">
                <label className="text-[10px] font-bold text-gray-500 uppercase tracking-wider block">Validity Date & Time</label>
                <input
                  type="datetime-local"
                  required
                  value={editFormData.validity}
                  onChange={(e) => setEditFormData({ ...editFormData, validity: e.target.value })}
                  className="w-full p-2.5 border border-gray-200 rounded-xl text-xs focus:outline-none focus:border-amber-700 bg-white font-nunito font-semibold cursor-pointer"
                />
              </div>

              <div className="flex gap-3 justify-end pt-4">
                <button
                  type="button"
                  onClick={() => { setEditModalOpen(false); setSelectedBill(null); }}
                  className="px-4 py-2 border border-gray-200 rounded-xl text-xs font-bold text-gray-500 hover:bg-gray-50 cursor-pointer active:scale-95 transition-all"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isSaving}
                  className="px-4 py-2 bg-amber-700 hover:bg-amber-800 text-white rounded-xl text-xs font-bold shadow-md shadow-amber-700/10 cursor-pointer active:scale-95 transition-all flex items-center gap-1.5"
                >
                  {isSaving ? "Saving..." : "Save Changes"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Delete Confirmation Modal */}
      {deleteModalOpen && (
        <div className="fixed inset-0 bg-black/40 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl border border-gray-100 w-full max-w-sm p-6 shadow-2xl animate-in fade-in zoom-in-95 duration-150">
            <div className="flex items-center gap-3 text-red-600 mb-4">
              <div className="w-10 h-10 rounded-full bg-red-50 flex items-center justify-center shrink-0">
                <AlertTriangle className="w-5 h-5" />
              </div>
              <h3 className="text-base font-bold font-poppins">Delete E-Way Bill</h3>
            </div>
            
            <p className="text-xs text-gray-600 leading-relaxed font-nunito mb-6">
              Are you sure you want to delete E-Way Bill <strong className="text-gray-800">{selectedBill?.ewayBillNo}</strong>? This action is permanent and cannot be undone.
            </p>

            <div className="flex gap-3 justify-end">
               <button
                 type="button"
                 onClick={() => { setDeleteModalOpen(false); setSelectedBill(null); }}
                 className="px-4 py-2 border border-gray-200 rounded-xl text-xs font-bold text-gray-500 hover:bg-gray-50 cursor-pointer active:scale-95 transition-all"
               >
                 Cancel
               </button>
               <button
                 type="button"
                 onClick={handleDeleteConfirm}
                 disabled={isDeleting}
                 className="px-4 py-2 bg-red-600 hover:bg-red-700 text-white rounded-xl text-xs font-bold shadow-md shadow-red-600/10 cursor-pointer active:scale-95 transition-all"
               >
                 {isDeleting ? "Deleting..." : "Delete E-Way Bill"}
               </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
