import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:image_picker/image_picker.dart';
import '../constants/app_colors.dart';
import '../constants/app_radius.dart';
import '../constants/app_spacing.dart';
import '../services/api_service.dart';
import '../widgets/custom_app_bar.dart';
import '../widgets/custom_card.dart';

class TripCompletionScreen extends StatefulWidget {
  final String tripId;
  final Map<String, dynamic>? tripData;

  const TripCompletionScreen({
    super.key,
    required this.tripId,
    this.tripData,
  });

  @override
  State<TripCompletionScreen> createState() => _TripCompletionScreenState();
}

class _TripCompletionScreenState extends State<TripCompletionScreen> {
  bool _isSubmitting = false;
  Map<String, dynamic>? _trip;

  // Local data holders
  Map<String, dynamic>? _podData;
  Map<String, dynamic>? _fuelData;
  Map<String, dynamic>? _weighbridgeData;
  Map<String, dynamic>? _tollData;

  @override
  void initState() {
    super.initState();
    _trip = widget.tripData;
    _fetchTripDetails();
    _fetchAutogeneratedTolls();
  }

  Future<void> _fetchTripDetails() async {
    final cleanId = widget.tripId.replaceAll('#', '').trim();
    try {
      final res = await ApiService.getTripDetails(cleanId);
      if (res != null && res['data'] != null) {
        setState(() {
          _trip = res['data'];
          if (_trip!['podDetails'] != null) {
            _podData = _trip!['podDetails'] as Map<String, dynamic>?;
          }
          if (_trip!['fuelDetails'] != null) {
            _fuelData = _trip!['fuelDetails'] as Map<String, dynamic>?;
          }
          if (_trip!['weighbridgeDetails'] != null) {
            _weighbridgeData = _trip!['weighbridgeDetails'] as Map<String, dynamic>?;
          }
          if (_trip!['tollDetails'] != null) {
            _tollData = _trip!['tollDetails'] as Map<String, dynamic>?;
          }
        });
      }
    } catch (_) {}
  }

  Future<void> _fetchAutogeneratedTolls() async {
    final cleanId = widget.tripId.replaceAll('#', '').trim();
    try {
      final res = await ApiService.getDriverTripTolls(cleanId);
      if (res != null && res['success'] == true) {
        final List list = res['data'] ?? [];
        if (list.isNotEmpty) {
          double total = 0.0;
          for (var item in list) {
            final amt = item['amountPaid'] ?? item['amount'] ?? 0.0;
            total += double.tryParse(amt.toString()) ?? 0.0;
          }
          final firstPlaza = list[0]['tollPlazaName'] ?? 'Toll Plaza';
          setState(() {
            _tollData = {
              'tollPlazaName': firstPlaza + (list.length > 1 ? ' + ${list.length - 1} more' : ''),
              'amountPaid': total,
              'dateTime': list[0]['dateTime'] ?? '',
              'isAutogenerated': true,
              'imageFiles': <dynamic>[],
              'imageNames': <String>[],
            };
          });
        }
      }
    } catch (_) {}
  }

  @override
  Widget build(BuildContext context) {
    final isDesktop = MediaQuery.of(context).size.width > 768;
    final cleanId = widget.tripId.replaceAll('#', '').trim();

    final isWeighbridgeRequired = _trip?['weighbridgeRequired'] ?? true;
    final podStatus = _podData != null ? 'Completed' : 'Pending';
    final fuelStatus = _fuelData != null ? 'Completed' : 'Pending';
    final weighbridgeStatus = !isWeighbridgeRequired
        ? 'Not Required'
        : (_weighbridgeData != null ? 'Completed' : 'Pending');
    final tollStatus = _tollData != null ? 'Completed' : 'Pending';

    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: CustomAppBar(
        centerTitle: false,
        title: Text(
          'Trip Completion',
          style: Theme.of(context).textTheme.titleLarge?.copyWith(
            color: AppColors.background,
            fontWeight: FontWeight.bold,
          ),
        ),
      ),
      body: SafeArea(
        child: Stack(
          children: [
            SingleChildScrollView(
              padding: EdgeInsets.symmetric(
                horizontal: isDesktop ? MediaQuery.of(context).size.width * 0.2 : AppSpacing.md,
                vertical: AppSpacing.md,
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  // Trip Summary Header Card
                  _buildSummaryHeader(),
                  const SizedBox(height: 20),

                  Text(
                    'COMPLETION CHECKLIST',
                    style: GoogleFonts.poppins(
                      fontSize: 11,
                      fontWeight: FontWeight.bold,
                      color: AppColors.secondaryText,
                      letterSpacing: 0.5,
                    ),
                  ),
                  const SizedBox(height: 8),

                  // 1. POD Card
                  _buildActionCard(
                    title: 'Proof of Delivery (POD)',
                    subtitle: _podData != null 
                        ? 'Customer Name: ${_podData!['customerName']}'
                        : 'Upload delivery receipt signed by customer',
                    icon: Icons.assignment_turned_in_rounded,
                    iconColor: Colors.blue,
                    status: podStatus,
                    onTap: () async {
                      final data = await Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (context) => PodEntryScreen(initialData: _podData),
                        ),
                      );
                      if (data != null) {
                        setState(() {
                          _isSubmitting = true;
                        });
                        try {
                          await ApiService.uploadTripPod(
                            tripId: cleanId,
                            customerName: data['customerName'],
                            receiverName: data['receiverName'],
                            imageFile: data['imageFile'],
                            imageName: data['imageName'],
                          );
                          await _fetchTripDetails();
                          if (mounted) {
                            ScaffoldMessenger.of(context).showSnackBar(
                              const SnackBar(
                                content: Text('✅ POD uploaded successfully!'),
                                backgroundColor: AppColors.success,
                              ),
                            );
                          }
                        } catch (e) {
                          if (mounted) {
                            ScaffoldMessenger.of(context).showSnackBar(
                              SnackBar(
                                content: Text('POD upload failed: $e'),
                                backgroundColor: AppColors.error,
                              ),
                            );
                          }
                        } finally {
                          setState(() {
                            _isSubmitting = false;
                          });
                        }
                      }
                    },
                  ),
                  const SizedBox(height: 12),

                  // 2. Fuel Card
                  _buildActionCard(
                    title: 'Fuel Entry',
                    subtitle: _fuelData != null
                        ? '${_fuelData!['liters']} L refueled at ${_fuelData!['fuelStation']}'
                        : 'Enter trip refuel details and receipts',
                    icon: Icons.local_gas_station_rounded,
                    iconColor: Colors.orange,
                    status: fuelStatus,
                    onTap: () async {
                      final data = await Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (context) => FuelEntryFormScreen(initialData: _fuelData),
                        ),
                      );
                      if (data != null) {
                        setState(() {
                          _isSubmitting = true;
                        });
                        try {
                          await ApiService.createTripFuelEntry(
                            fuelStation: data['fuelStation'],
                            amount: data['amount'],
                            liters: data['liters'],
                            odometer: data['odometer'],
                            tripId: cleanId,
                            dateTime: data['dateTime'],
                            imageFile: data['imageFile'],
                            imageName: data['imageName'],
                          );
                          await _fetchTripDetails();
                          if (mounted) {
                            ScaffoldMessenger.of(context).showSnackBar(
                              const SnackBar(
                                content: Text('✅ Fuel entry uploaded successfully!'),
                                backgroundColor: AppColors.success,
                              ),
                            );
                          }
                        } catch (e) {
                          if (mounted) {
                            ScaffoldMessenger.of(context).showSnackBar(
                              SnackBar(
                                content: Text('Fuel upload failed: $e'),
                                backgroundColor: AppColors.error,
                              ),
                            );
                          }
                        } finally {
                          setState(() {
                            _isSubmitting = false;
                          });
                        }
                      }
                    },
                  ),
                  const SizedBox(height: 12),

                  // Weighbridge Card
                  _buildActionCard(
                    title: 'Weighbridge Slip',
                    subtitle: !isWeighbridgeRequired
                        ? 'Weighbridge slip is not required for this trip'
                        : (_weighbridgeData != null
                            ? 'Net Weight: ${_weighbridgeData!['netWeight']} kg at ${_weighbridgeData!['location']}'
                            : 'Upload slip, tare, gross, and net weights'),
                    icon: Icons.scale_rounded,
                    iconColor: !isWeighbridgeRequired ? Colors.grey : Colors.purple,
                    status: weighbridgeStatus,
                    onTap: !isWeighbridgeRequired
                        ? () {}
                        : () async {
                            final data = await Navigator.push(
                              context,
                              MaterialPageRoute(
                                builder: (context) => WeighbridgeEntryScreen(initialData: _weighbridgeData),
                              ),
                            );
                            if (data != null) {
                              setState(() {
                                _isSubmitting = true;
                              });
                              try {
                                await ApiService.uploadWeighbridgeSlip(
                                  tripId: cleanId,
                                  grossWeight: data['grossWeight'],
                                  tareWeight: data['tareWeight'],
                                  netWeight: data['netWeight'],
                                  location: data['location'],
                                  imageFile: data['imageFile'],
                                  imageName: data['imageName'],
                                );
                                await _fetchTripDetails();
                                if (mounted) {
                                  ScaffoldMessenger.of(context).showSnackBar(
                                    const SnackBar(
                                      content: Text('✅ Weighbridge Slip uploaded successfully!'),
                                      backgroundColor: AppColors.success,
                                    ),
                                  );
                                }
                              } catch (e) {
                                if (mounted) {
                                  ScaffoldMessenger.of(context).showSnackBar(
                                    SnackBar(
                                      content: Text('Weighbridge upload failed: $e'),
                                      backgroundColor: AppColors.error,
                                    ),
                                  );
                                }
                              } finally {
                                setState(() {
                                  _isSubmitting = false;
                                });
                              }
                            }
                          },
                  ),
                  const SizedBox(height: 12),

                  // 3. Toll Card
                  _buildActionCard(
                    title: 'Toll Receipts',
                    subtitle: _tollData != null
                        ? (_tollData!['isAutogenerated'] == true
                            ? '₹${_tollData!['amountPaid']} automatically logged via FASTag'
                            : '₹${_tollData!['amountPaid']} paid at ${_tollData!['tollPlazaName']}')
                        : 'Upload receipts and amounts for tolls',
                    icon: Icons.toll_rounded,
                    iconColor: Colors.green,
                    status: tollStatus,
                    onTap: () async {
                      final result = await showDialog<String>(
                        context: context,
                        builder: (ctx) => TollTransactionsDialog(tripId: widget.tripId),
                      );

                      if (result == 'upload_manual') {
                        if (!mounted) return;
                        final data = await Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (context) => TollReceiptsFormScreen(initialData: _tollData),
                          ),
                        );
                        if (data != null) {
                          setState(() {
                            _isSubmitting = true;
                          });
                          try {
                            await ApiService.createTripTollEntry(
                              tollPlazaName: data['tollPlazaName'],
                              amountPaid: data['amountPaid'],
                              tripId: cleanId,
                              dateTime: data['dateTime'],
                              imageFiles: data['imageFiles'],
                              imageNames: data['imageNames'],
                            );
                            await _fetchTripDetails();
                            if (mounted) {
                              ScaffoldMessenger.of(context).showSnackBar(
                                const SnackBar(
                                  content: Text('✅ Toll Receipt uploaded successfully!'),
                                  backgroundColor: AppColors.success,
                                ),
                              );
                            }
                          } catch (e) {
                            if (mounted) {
                              ScaffoldMessenger.of(context).showSnackBar(
                                SnackBar(
                                  content: Text('Toll upload failed: $e'),
                                  backgroundColor: AppColors.error,
                                ),
                              );
                            }
                          } finally {
                            setState(() {
                              _isSubmitting = false;
                            });
                          }
                        }
                      }
                    },
                  ),
                  const SizedBox(height: 32),

                  // Submit All Documents Button
                  ElevatedButton(
                    onPressed: _isSubmitting ? null : _handleSubmitAll,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppColors.primary,
                      minimumSize: const Size(double.infinity, 48),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(AppRadius.sm),
                      ),
                    ),
                    child: Text(
                      _isSubmitting ? 'UPLOADING...' : 'SUBMIT ALL DOCUMENTS',
                      style: GoogleFonts.poppins(
                        fontWeight: FontWeight.bold,
                        color: Colors.white,
                        fontSize: 14,
                      ),
                    ),
                  ),
                  const SizedBox(height: 40),
                ],
              ),
            ),
            if (_isSubmitting)
              Container(
                color: Colors.black.withValues(alpha: 0.5),
                child: const Center(
                  child: CircularProgressIndicator(color: AppColors.primary),
                ),
              ),
          ],
        ),
      ),
    );
  }

  Widget _buildSummaryHeader() {
    return CustomCard(
      padding: const EdgeInsets.all(16.0),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'TRIP ID',
                style: GoogleFonts.poppins(
                  fontSize: 10.5,
                  fontWeight: FontWeight.bold,
                  color: AppColors.secondaryText,
                ),
              ),
              const SizedBox(height: 4),
              Text(
                widget.tripId,
                style: GoogleFonts.poppins(
                  fontSize: 15,
                  fontWeight: FontWeight.bold,
                  color: AppColors.primaryText,
                ),
              ),
            ],
          ),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
            decoration: BoxDecoration(
              color: AppColors.success.withValues(alpha: 0.1),
              borderRadius: BorderRadius.circular(AppRadius.round),
            ),
            child: Text(
              'Awaiting Submissions',
              style: GoogleFonts.poppins(
                color: AppColors.success,
                fontWeight: FontWeight.bold,
                fontSize: 11,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildActionCard({
    required String title,
    required String subtitle,
    required IconData icon,
    required Color iconColor,
    required String status,
    required VoidCallback onTap,
  }) {
    final isCompleted = status == 'Completed';

    return GestureDetector(
      onTap: onTap,
      child: CustomCard(
        padding: const EdgeInsets.all(16.0),
        child: Row(
          children: [
            Container(
              width: 40,
              height: 40,
              decoration: BoxDecoration(
                color: iconColor.withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(8),
              ),
              child: Icon(icon, color: iconColor, size: 22),
            ),
            const SizedBox(width: 14),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    title,
                    style: GoogleFonts.poppins(
                      fontSize: 13.5,
                      fontWeight: FontWeight.bold,
                      color: AppColors.primaryText,
                    ),
                  ),
                  const SizedBox(height: 2),
                  Text(
                    subtitle,
                    style: GoogleFonts.nunito(
                      fontSize: 11.5,
                      color: AppColors.secondaryText,
                    ),
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                  ),
                ],
              ),
            ),
            const SizedBox(width: 10),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
              decoration: BoxDecoration(
                color: isCompleted 
                    ? AppColors.success.withValues(alpha: 0.1)
                    : AppColors.secondary.withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(20),
              ),
              child: Row(
                children: [
                  if (isCompleted)
                    const Icon(Icons.check, size: 12, color: AppColors.success),
                  if (isCompleted)
                    const SizedBox(width: 4),
                  Text(
                    status,
                    style: GoogleFonts.poppins(
                      fontSize: 10.5,
                      fontWeight: FontWeight.bold,
                      color: isCompleted ? AppColors.success : AppColors.secondary,
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Future<void> _handleSubmitAll() async {
    if (_isSubmitting) return;

    final isWeighbridgeRequired = _trip?['weighbridgeRequired'] ?? true;
    final hasPod = _trip?['podDetails'] != null || _podData != null;
    final hasWeighbridge = !isWeighbridgeRequired || _trip?['weighbridgeDetails'] != null || _weighbridgeData != null;

    if (!hasPod) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('⚠️ Proof of Delivery (POD) document is required.'),
          backgroundColor: AppColors.error,
        ),
      );
      return;
    }

    if (isWeighbridgeRequired && !hasWeighbridge) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('⚠️ Weighbridge Slip document is required.'),
          backgroundColor: AppColors.error,
        ),
      );
      return;
    }

    setState(() {
      _isSubmitting = true;
    });

    final cleanId = widget.tripId.replaceAll('#', '').trim();

    try {
      // Update Trip Status to Completed
      await ApiService.updateTripStatus(cleanId, 'Completed');

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('🎉 Documents uploaded & Trip Completed successfully!'),
            backgroundColor: AppColors.success,
            behavior: SnackBarBehavior.floating,
          ),
        );
        Navigator.pop(context, true);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Completion failed: ${e.toString().replaceAll('Exception: ', '')}'),
            backgroundColor: AppColors.error,
            behavior: SnackBarBehavior.floating,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isSubmitting = false;
        });
      }
    }
  }
}

// ----------------------------------------------------
// 1. POD Sub Screen Form
// ----------------------------------------------------
class PodEntryScreen extends StatefulWidget {
  final Map<String, dynamic>? initialData;
  const PodEntryScreen({super.key, this.initialData});

  @override
  State<PodEntryScreen> createState() => _PodEntryScreenState();
}

class _PodEntryScreenState extends State<PodEntryScreen> {
  final _formKey = GlobalKey<FormState>();
  final _customerController = TextEditingController(text: 'Acme Logistics');
  final _receiverController = TextEditingController(text: 'Verified Receiver');
  dynamic _imageBytes;
  String? _imageName;

  @override
  void initState() {
    super.initState();
    if (widget.initialData != null) {
      _customerController.text = widget.initialData!['customerName'] ?? '';
      _receiverController.text = widget.initialData!['receiverName'] ?? '';
      _imageBytes = widget.initialData!['imageFile'];
      _imageName = widget.initialData!['imageName'];
    }
  }

  @override
  void dispose() {
    _customerController.dispose();
    _receiverController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: CustomAppBar(
        centerTitle: false,
        title: Text(
          'POD Entry',
          style: Theme.of(context).textTheme.titleLarge?.copyWith(
            color: AppColors.background,
            fontWeight: FontWeight.bold,
          ),
        ),
      ),
      body: Form(
        key: _formKey,
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              _buildInputField(
                controller: _customerController,
                label: 'Customer Name',
                hint: 'e.g. Acme Corp',
                validator: (val) => val == null || val.trim().isEmpty ? 'Customer Name is required' : null,
              ),
              const SizedBox(height: 12),
              _buildInputField(
                controller: _receiverController,
                label: 'Receiver Name',
                hint: 'e.g. John Doe',
                validator: (val) => val == null || val.trim().isEmpty ? 'Receiver Name is required' : null,
              ),
              const SizedBox(height: 20),
              Text(
                'PROOF OF DELIVERY SLIP',
                style: GoogleFonts.poppins(
                  fontSize: 10.5,
                  fontWeight: FontWeight.bold,
                  color: AppColors.secondaryText,
                ),
              ),
              const SizedBox(height: 8),
              _imageBytes == null
                  ? InkWell(
                      onTap: _pickImage,
                      child: Container(
                        height: 120,
                        decoration: BoxDecoration(
                          border: Border.all(color: AppColors.divider),
                          borderRadius: BorderRadius.circular(AppRadius.md),
                          color: Colors.grey.shade50,
                        ),
                        child: Center(
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              const Icon(Icons.add_photo_alternate_outlined, color: AppColors.secondary, size: 28),
                              const SizedBox(height: 6),
                              Text('Tap to select POD receipt', style: GoogleFonts.nunito(fontSize: 12, color: AppColors.secondaryText)),
                            ],
                          ),
                        ),
                      ),
                    )
                  : Container(
                      height: 120,
                      decoration: BoxDecoration(
                        border: Border.all(color: AppColors.divider),
                        borderRadius: BorderRadius.circular(AppRadius.md),
                      ),
                      padding: const EdgeInsets.all(8),
                      child: Row(
                        children: [
                          const Icon(Icons.description_outlined, color: Colors.blue, size: 36),
                          const SizedBox(width: 12),
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                Text(
                                  _imageName ?? 'pod_receipt.jpg',
                                  style: GoogleFonts.poppins(fontSize: 13, fontWeight: FontWeight.bold, color: AppColors.primaryText),
                                  maxLines: 1,
                                  overflow: TextOverflow.ellipsis,
                                ),
                                const SizedBox(height: 4),
                                Text('Attached successfully', style: GoogleFonts.nunito(fontSize: 11, color: AppColors.success)),
                              ],
                            ),
                          ),
                          IconButton(
                            icon: const Icon(Icons.delete_outline, color: AppColors.error),
                            onPressed: () {
                              setState(() {
                                _imageBytes = null;
                                _imageName = null;
                              });
                            },
                          ),
                        ],
                      ),
                    ),
              const SizedBox(height: 32),
              ElevatedButton(
                onPressed: () {
                  if (_formKey.currentState!.validate() && _imageBytes != null) {
                    Navigator.pop(context, {
                      'customerName': _customerController.text.trim(),
                      'receiverName': _receiverController.text.trim(),
                      'imageFile': _imageBytes,
                      'imageName': _imageName,
                    });
                  } else if (_imageBytes == null) {
                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(content: Text('⚠️ Please attach a POD receipt image.')),
                    );
                  }
                },
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppColors.primary,
                  minimumSize: const Size(double.infinity, 48),
                ),
                child: Text('SAVE DETAILS', style: GoogleFonts.poppins(fontWeight: FontWeight.bold, color: Colors.white)),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Future<void> _pickImage() async {
    final XFile? file = await ImagePicker().pickImage(source: ImageSource.gallery, imageQuality: 85);
    if (file != null) {
      final bytes = await file.readAsBytes();
      setState(() {
        _imageBytes = bytes;
        _imageName = file.name;
      });
    }
  }

  Widget _buildInputField({
    required TextEditingController controller,
    required String label,
    required String hint,
    String? Function(String?)? validator,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label.toUpperCase(),
          style: GoogleFonts.poppins(
            fontSize: 10.5,
            fontWeight: FontWeight.bold,
            color: AppColors.secondaryText,
          ),
        ),
        const SizedBox(height: 4),
        TextFormField(
          controller: controller,
          validator: validator,
          style: GoogleFonts.poppins(fontSize: 13, fontWeight: FontWeight.bold, color: AppColors.primaryText),
          decoration: InputDecoration(
            hintText: hint,
            hintStyle: GoogleFonts.poppins(fontSize: 13, color: AppColors.secondaryText),
            isDense: true,
            contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
            filled: true,
            fillColor: Colors.white,
            enabledBorder: OutlineInputBorder(borderSide: const BorderSide(color: AppColors.divider)),
            focusedBorder: OutlineInputBorder(borderSide: const BorderSide(color: AppColors.secondary)),
          ),
        ),
      ],
    );
  }
}

// ----------------------------------------------------
// 2. Fuel Entry Sub Screen Form
// ----------------------------------------------------
class FuelEntryFormScreen extends StatefulWidget {
  final Map<String, dynamic>? initialData;
  const FuelEntryFormScreen({super.key, this.initialData});

  @override
  State<FuelEntryFormScreen> createState() => _FuelEntryFormScreenState();
}

class _FuelEntryFormScreenState extends State<FuelEntryFormScreen> {
  final _formKey = GlobalKey<FormState>();
  final _stationController = TextEditingController();
  final _litersController = TextEditingController();
  final _amountController = TextEditingController();
  final _odometerController = TextEditingController();
  final _dateTimeController = TextEditingController();
  dynamic _imageBytes;
  String? _imageName;

  @override
  void initState() {
    super.initState();
    _dateTimeController.text = DateTime.now().toString().split('.')[0];
    _fetchVehicleInfo();
    if (widget.initialData != null) {
      _stationController.text = widget.initialData!['fuelStation'] ?? '';
      _litersController.text = widget.initialData!['liters']?.toString() ?? '';
      _amountController.text = widget.initialData!['amount']?.toString() ?? '';
      _odometerController.text = widget.initialData!['odometer']?.toString() ?? '';
      _dateTimeController.text = widget.initialData!['dateTime'] ?? '';
      _imageBytes = widget.initialData!['imageFile'];
      _imageName = widget.initialData!['imageName'];
    }
  }

  Future<void> _fetchVehicleInfo() async {
    if (widget.initialData != null) return;
    try {
      final res = await ApiService.getAssignedVehicle();
      if (mounted && res != null && res['success'] == true) {
        final data = res['data'];
        if (data != null && data['assigned'] == true && data['vehicle'] != null) {
          final v = data['vehicle'];
          setState(() {
            if (v['odometer'] != null) {
              _odometerController.text = v['odometer'].toString();
            }
          });
        }
      }
    } catch (_) {}
  }

  @override
  void dispose() {
    _stationController.dispose();
    _litersController.dispose();
    _amountController.dispose();
    _odometerController.dispose();
    _dateTimeController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: CustomAppBar(
        centerTitle: false,
        title: Text(
          'Fuel Entry',
          style: Theme.of(context).textTheme.titleLarge?.copyWith(
            color: AppColors.background,
            fontWeight: FontWeight.bold,
          ),
        ),
      ),
      body: Form(
        key: _formKey,
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              _buildInputField(
                controller: _stationController,
                label: 'Station Name',
                hint: 'e.g. Shell Station',
                validator: (val) => val == null || val.trim().isEmpty ? 'Station Name is required' : null,
              ),
              const SizedBox(height: 12),
              Row(
                children: [
                  Expanded(
                    child: _buildInputField(
                      controller: _litersController,
                      label: 'Liters',
                      hint: 'e.g. 45.0',
                      keyboardType: const TextInputType.numberWithOptions(decimal: true),
                      validator: (val) {
                        if (val == null || val.trim().isEmpty) return 'Required';
                        if (double.tryParse(val) == null || double.parse(val) <= 0) return 'Invalid';
                        return null;
                      },
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: _buildInputField(
                      controller: _amountController,
                      label: 'Amount Paid (₹)',
                      hint: 'e.g. 4250',
                      keyboardType: const TextInputType.numberWithOptions(decimal: true),
                      validator: (val) {
                        if (val == null || val.trim().isEmpty) return 'Required';
                        if (double.tryParse(val) == null || double.parse(val) <= 0) return 'Invalid';
                        return null;
                      },
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 12),
              Row(
                children: [
                  Expanded(
                    child: _buildInputField(
                      controller: _odometerController,
                      label: 'Odometer Reading',
                      hint: 'e.g. 142850',
                      keyboardType: TextInputType.number,
                      validator: (val) {
                        if (val == null || val.trim().isEmpty) return 'Required';
                        if (double.tryParse(val) == null || double.parse(val) <= 0) return 'Invalid';
                        return null;
                      },
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: _buildInputField(
                      controller: _dateTimeController,
                      label: 'Refuel Date/Time',
                      hint: 'YYYY-MM-DD HH:MM',
                      validator: (val) => val == null || val.trim().isEmpty ? 'Date is required' : null,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 20),
              Text(
                'RECEIPT UPLOAD',
                style: GoogleFonts.poppins(
                  fontSize: 10.5,
                  fontWeight: FontWeight.bold,
                  color: AppColors.secondaryText,
                ),
              ),
              const SizedBox(height: 8),
              _imageBytes == null
                  ? InkWell(
                      onTap: _pickImage,
                      child: Container(
                        height: 120,
                        decoration: BoxDecoration(
                          border: Border.all(color: AppColors.divider),
                          borderRadius: BorderRadius.circular(AppRadius.md),
                          color: Colors.grey.shade50,
                        ),
                        child: Center(
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              const Icon(Icons.add_photo_alternate_outlined, color: AppColors.secondary, size: 28),
                              const SizedBox(height: 6),
                              Text('Tap to upload fuel receipt', style: GoogleFonts.nunito(fontSize: 12, color: AppColors.secondaryText)),
                            ],
                          ),
                        ),
                      ),
                    )
                  : Container(
                      height: 120,
                      decoration: BoxDecoration(
                        border: Border.all(color: AppColors.divider),
                        borderRadius: BorderRadius.circular(AppRadius.md),
                      ),
                      padding: const EdgeInsets.all(8),
                      child: Row(
                        children: [
                          const Icon(Icons.description_outlined, color: Colors.blue, size: 36),
                          const SizedBox(width: 12),
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                  Text(
                                    _imageName ?? 'fuel_receipt.jpg',
                                    style: GoogleFonts.poppins(fontSize: 13, fontWeight: FontWeight.bold, color: AppColors.primaryText),
                                    maxLines: 1,
                                    overflow: TextOverflow.ellipsis,
                                  ),
                                  const SizedBox(height: 4),
                                  Text('Attached successfully', style: GoogleFonts.nunito(fontSize: 11, color: AppColors.success)),
                              ],
                            ),
                          ),
                          IconButton(
                            icon: const Icon(Icons.delete_outline, color: AppColors.error),
                            onPressed: () {
                              setState(() {
                                _imageBytes = null;
                                _imageName = null;
                              });
                            },
                          ),
                        ],
                      ),
                    ),
              const SizedBox(height: 32),
              ElevatedButton(
                onPressed: () {
                  if (_formKey.currentState!.validate()) {
                    Navigator.pop(context, {
                      'fuelStation': _stationController.text.trim(),
                      'liters': double.tryParse(_litersController.text) ?? 0.0,
                      'amount': double.tryParse(_amountController.text) ?? 0.0,
                      'odometer': double.tryParse(_odometerController.text) ?? 0.0,
                      'dateTime': _dateTimeController.text.trim(),
                      'imageFile': _imageBytes,
                      'imageName': _imageName,
                    });
                  }
                },
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppColors.primary,
                  minimumSize: const Size(double.infinity, 48),
                ),
                child: Text('SAVE FUEL ENTRY', style: GoogleFonts.poppins(fontWeight: FontWeight.bold, color: Colors.white)),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Future<void> _pickImage() async {
    final XFile? file = await ImagePicker().pickImage(source: ImageSource.gallery, imageQuality: 85);
    if (file != null) {
      final bytes = await file.readAsBytes();
      setState(() {
        _imageBytes = bytes;
        _imageName = file.name;
      });
    }
  }

  Widget _buildInputField({
    required TextEditingController controller,
    required String label,
    required String hint,
    TextInputType keyboardType = TextInputType.text,
    String? Function(String?)? validator,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label.toUpperCase(),
          style: GoogleFonts.poppins(
            fontSize: 10.5,
            fontWeight: FontWeight.bold,
            color: AppColors.secondaryText,
          ),
        ),
        const SizedBox(height: 4),
        TextFormField(
          controller: controller,
          keyboardType: keyboardType,
          validator: validator,
          style: GoogleFonts.poppins(fontSize: 13, fontWeight: FontWeight.bold, color: AppColors.primaryText),
          decoration: InputDecoration(
            hintText: hint,
            hintStyle: GoogleFonts.poppins(fontSize: 13, color: AppColors.secondaryText),
            isDense: true,
            contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
            filled: true,
            fillColor: Colors.white,
            enabledBorder: OutlineInputBorder(borderSide: const BorderSide(color: AppColors.divider)),
            focusedBorder: OutlineInputBorder(borderSide: const BorderSide(color: AppColors.secondary)),
          ),
        ),
      ],
    );
  }
}

// ----------------------------------------------------
// Toll Transactions Dialog (Dynamic FASTag Ledger)
// ----------------------------------------------------
class TollTransactionsDialog extends StatefulWidget {
  final String tripId;
  const TollTransactionsDialog({super.key, required this.tripId});

  @override
  State<TollTransactionsDialog> createState() => _TollTransactionsDialogState();
}

class _TollTransactionsDialogState extends State<TollTransactionsDialog> {
  bool _isLoading = true;
  List<dynamic> _fastagTolls = [];
  double _totalAmount = 0.0;
  String? _errorMessage;

  @override
  void initState() {
    super.initState();
    _fetchTolls();
  }

  Future<void> _fetchTolls() async {
    final cleanId = widget.tripId.replaceAll('#', '').trim();
    try {
      final res = await ApiService.getDriverTripTolls(cleanId);
      if (res != null && res['success'] == true) {
        final List list = res['data'] ?? [];
        final fastagList = list.where((item) => item['paymentMethod'] == 'FASTag').toList();
        
        double total = 0.0;
        for (var item in fastagList) {
          final amt = item['amountPaid'] ?? item['amount'] ?? 0.0;
          total += double.tryParse(amt.toString()) ?? 0.0;
        }

        if (mounted) {
          setState(() {
            _fastagTolls = fastagList;
            _totalAmount = total;
            _isLoading = false;
          });
        }
      } else {
        if (mounted) {
          setState(() {
            _isLoading = false;
          });
        }
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _errorMessage = e.toString().replaceAll('Exception: ', '');
          _isLoading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      backgroundColor: Colors.white,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      titlePadding: const EdgeInsets.only(top: 20, left: 24, right: 24),
      contentPadding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
      actionsPadding: const EdgeInsets.only(bottom: 16, right: 24, left: 24),
      title: Row(
        children: [
          const Icon(Icons.toll_outlined, color: AppColors.primary),
          const SizedBox(width: 8),
          Text(
            'Toll Transactions',
            style: GoogleFonts.poppins(
              fontWeight: FontWeight.bold,
              fontSize: 16,
              color: AppColors.primaryText,
            ),
          ),
        ],
      ),
      content: SizedBox(
        width: double.maxFinite,
        child: _isLoading
            ? const SizedBox(
                height: 150,
                child: Center(
                  child: CircularProgressIndicator(color: AppColors.primary),
                ),
              )
            : _errorMessage != null
                ? Text(_errorMessage!, style: GoogleFonts.nunito(color: AppColors.error))
                : _fastagTolls.isEmpty
                    ? Column(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          const SizedBox(height: 12),
                          const Icon(
                            Icons.warning_amber_rounded,
                            size: 48,
                            color: Colors.orange,
                          ),
                          const SizedBox(height: 12),
                          Text(
                            'No toll transactions found',
                            style: GoogleFonts.poppins(
                              fontSize: 14.5,
                              fontWeight: FontWeight.bold,
                              color: AppColors.primaryText,
                            ),
                          ),
                          const SizedBox(height: 6),
                          Text(
                            'No automated FASTag logs were detected for this trip. If you paid cash or crossed tolls manually, please upload the receipt details.',
                            textAlign: TextAlign.center,
                            style: GoogleFonts.nunito(
                              fontSize: 12,
                              color: AppColors.secondaryText,
                            ),
                          ),
                          const SizedBox(height: 16),
                        ],
                      )
                    : Column(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Flexible(
                            child: ConstrainedBox(
                              constraints: const BoxConstraints(maxHeight: 280),
                              child: ListView.separated(
                                shrinkWrap: true,
                                itemCount: _fastagTolls.length,
                                separatorBuilder: (ctx, index) => const Divider(height: 1, color: AppColors.divider),
                                itemBuilder: (ctx, index) {
                                  final item = _fastagTolls[index];
                                  final plaza = item['tollPlazaName'] ?? 'General Toll Plaza';
                                  final amt = item['amountPaid'] ?? item['amount'] ?? 0;
                                  final dateStr = item['dateTime'] != null ? item['dateTime'].toString().split('T')[0] : 'Today';
                                  final timeStr = item['dateTime'] != null && item['dateTime'].toString().contains('T')
                                      ? item['dateTime'].toString().split('T')[1].substring(0, 5)
                                      : 'Recently';
                                  final txId = item['fastagTransactionId'] ?? 'N/A';

                                  return Padding(
                                    padding: const EdgeInsets.symmetric(vertical: 10),
                                    child: Column(
                                      crossAxisAlignment: CrossAxisAlignment.start,
                                      children: [
                                        Row(
                                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                          children: [
                                            Expanded(
                                              child: Text(
                                                plaza,
                                                style: GoogleFonts.poppins(
                                                  fontWeight: FontWeight.bold,
                                                  fontSize: 13,
                                                  color: AppColors.primaryText,
                                                ),
                                              ),
                                            ),
                                            Text(
                                              '₹$amt',
                                              style: GoogleFonts.poppins(
                                                fontWeight: FontWeight.bold,
                                                fontSize: 13.5,
                                                color: AppColors.secondary,
                                              ),
                                            ),
                                          ],
                                        ),
                                        const SizedBox(height: 4),
                                        Row(
                                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                          children: [
                                            Text(
                                              '$dateStr • $timeStr',
                                              style: GoogleFonts.nunito(
                                                fontSize: 11,
                                                color: AppColors.secondaryText,
                                              ),
                                            ),
                                            if (txId != 'N/A')
                                              Text(
                                                'Tx ID: $txId',
                                                style: GoogleFonts.poppins(
                                                  fontSize: 10,
                                                  fontWeight: FontWeight.w600,
                                                  color: Colors.blue.shade700,
                                                ),
                                              ),
                                          ],
                                        ),
                                      ],
                                    ),
                                  );
                                },
                              ),
                            ),
                          ),
                          const Divider(height: 24, thickness: 1.5, color: AppColors.divider),
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Text(
                                'Total Toll Amount',
                                style: GoogleFonts.poppins(
                                  fontWeight: FontWeight.bold,
                                  fontSize: 14,
                                  color: AppColors.primaryText,
                                ),
                              ),
                              Text(
                                '₹${_totalAmount.toStringAsFixed(2)}',
                                style: GoogleFonts.poppins(
                                  fontWeight: FontWeight.w800,
                                  fontSize: 16,
                                  color: AppColors.primary,
                                ),
                              ),
                            ],
                          ),
                          const SizedBox(height: 12),
                          Container(
                            padding: const EdgeInsets.all(10),
                            decoration: BoxDecoration(
                              color: Colors.blue.withValues(alpha: 0.08),
                              borderRadius: BorderRadius.circular(8),
                            ),
                            child: Row(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const Icon(Icons.info_outline, size: 16, color: Colors.blue),
                                const SizedBox(width: 8),
                                Expanded(
                                  child: Text(
                                    'Toll transactions automatically logged via FASTag. Manual entry is disabled.',
                                    style: GoogleFonts.nunito(
                                      fontSize: 11,
                                      fontWeight: FontWeight.w600,
                                      color: Colors.blue.shade900,
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
      ),
      actions: [
        if (!_isLoading && _errorMessage == null && _fastagTolls.isEmpty)
          ElevatedButton.icon(
            onPressed: () => Navigator.pop(context, 'upload_manual'),
            icon: const Icon(Icons.upload_file, color: Colors.white, size: 16),
            label: Text(
              'UPLOAD MANUAL TOLL RECEIPT',
              style: GoogleFonts.poppins(
                fontWeight: FontWeight.bold,
                fontSize: 11.5,
                color: Colors.white,
              ),
            ),
            style: ElevatedButton.styleFrom(
              backgroundColor: AppColors.secondary,
              minimumSize: const Size(double.infinity, 44),
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
            ),
          )
        else
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: Text(
              'OK',
              style: GoogleFonts.poppins(
                fontWeight: FontWeight.bold,
                color: AppColors.secondary,
              ),
            ),
          ),
      ],
    );
  }
}

// ----------------------------------------------------
// 3. Toll Entry Sub Screen Form
// ----------------------------------------------------
class TollReceiptsFormScreen extends StatefulWidget {
  final Map<String, dynamic>? initialData;
  const TollReceiptsFormScreen({super.key, this.initialData});

  @override
  State<TollReceiptsFormScreen> createState() => _TollReceiptsFormScreenState();
}

class _TollReceiptsFormScreenState extends State<TollReceiptsFormScreen> {
  final _formKey = GlobalKey<FormState>();
  final _plazaController = TextEditingController();
  final _amountController = TextEditingController();
  final _dateTimeController = TextEditingController();
  final List<dynamic> _imageFiles = [];
  final List<String> _imageNames = [];

  @override
  void initState() {
    super.initState();
    _dateTimeController.text = DateTime.now().toString().split('.')[0];
    if (widget.initialData != null) {
      _plazaController.text = widget.initialData!['tollPlazaName'] ?? '';
      _amountController.text = widget.initialData!['amountPaid']?.toString() ?? '';
      _dateTimeController.text = widget.initialData!['dateTime'] ?? '';
      if (widget.initialData!['imageFiles'] != null) {
        _imageFiles.addAll(widget.initialData!['imageFiles'] as List);
      }
      if (widget.initialData!['imageNames'] != null) {
        _imageNames.addAll(widget.initialData!['imageNames'] as List<String>);
      }
    }
  }

  @override
  void dispose() {
    _plazaController.dispose();
    _amountController.dispose();
    _dateTimeController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: CustomAppBar(
        centerTitle: false,
        title: Text(
          'Toll Receipts',
          style: Theme.of(context).textTheme.titleLarge?.copyWith(
            color: AppColors.background,
            fontWeight: FontWeight.bold,
          ),
        ),
      ),
      body: Form(
        key: _formKey,
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              _buildInputField(
                controller: _plazaController,
                label: 'Toll Plaza Name',
                hint: 'e.g. L&T Toll Plaza',
                validator: (val) => val == null || val.trim().isEmpty ? 'Toll Plaza Name is required' : null,
              ),
              const SizedBox(height: 12),
              Row(
                children: [
                  Expanded(
                    child: _buildInputField(
                      controller: _amountController,
                      label: 'Amount Paid (₹)',
                      hint: 'e.g. 360',
                      keyboardType: const TextInputType.numberWithOptions(decimal: true),
                      validator: (val) {
                        if (val == null || val.trim().isEmpty) return 'Required';
                        if (double.tryParse(val) == null || double.parse(val) <= 0) return 'Invalid';
                        return null;
                      },
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: _buildInputField(
                      controller: _dateTimeController,
                      label: 'Crossed Date/Time',
                      hint: 'YYYY-MM-DD HH:MM',
                      validator: (val) => val == null || val.trim().isEmpty ? 'Date is required' : null,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 20),
              Text(
                'RECEIPTS UPLOAD (Multiple allowed)',
                style: GoogleFonts.poppins(
                  fontSize: 10.5,
                  fontWeight: FontWeight.bold,
                  color: AppColors.secondaryText,
                ),
              ),
              const SizedBox(height: 8),
              InkWell(
                onTap: _pickImage,
                child: Container(
                  height: 80,
                  decoration: BoxDecoration(
                    border: Border.all(color: AppColors.divider),
                    borderRadius: BorderRadius.circular(AppRadius.md),
                    color: Colors.grey.shade50,
                  ),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      const Icon(Icons.add_photo_alternate_outlined, color: AppColors.secondary, size: 24),
                      const SizedBox(width: 8),
                      Text('Attach Toll Receipt Image', style: GoogleFonts.nunito(fontSize: 12.5, fontWeight: FontWeight.bold, color: AppColors.secondary)),
                    ],
                  ),
                ),
              ),
              if (_imageFiles.isNotEmpty) ...[
                const SizedBox(height: 12),
                ListView.builder(
                  shrinkWrap: true,
                  physics: const NeverScrollableScrollPhysics(),
                  itemCount: _imageFiles.length,
                  itemBuilder: (ctx, index) {
                    return Container(
                      margin: const EdgeInsets.symmetric(vertical: 4.0),
                      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                      decoration: BoxDecoration(
                        border: Border.all(color: AppColors.divider),
                        borderRadius: BorderRadius.circular(AppRadius.md),
                        color: Colors.white,
                      ),
                      child: Row(
                        children: [
                          const Icon(Icons.receipt_long_outlined, color: Colors.blue, size: 28),
                          const SizedBox(width: 12),
                          Expanded(
                            child: Text(
                              _imageNames[index],
                              style: GoogleFonts.poppins(fontSize: 12.5, fontWeight: FontWeight.bold, color: AppColors.primaryText),
                              maxLines: 1,
                              overflow: TextOverflow.ellipsis,
                            ),
                          ),
                          IconButton(
                            icon: const Icon(Icons.close, color: AppColors.error, size: 18),
                            onPressed: () {
                              setState(() {
                                _imageFiles.removeAt(index);
                                _imageNames.removeAt(index);
                              });
                            },
                          ),
                        ],
                      ),
                    );
                  },
                ),
              ],
              const SizedBox(height: 32),
              ElevatedButton(
                onPressed: () {
                  if (_formKey.currentState!.validate()) {
                    Navigator.pop(context, {
                      'tollPlazaName': _plazaController.text.trim(),
                      'amountPaid': double.tryParse(_amountController.text) ?? 0.0,
                      'dateTime': _dateTimeController.text.trim(),
                      'imageFiles': _imageFiles,
                      'imageNames': _imageNames,
                    });
                  }
                },
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppColors.primary,
                  minimumSize: const Size(double.infinity, 48),
                ),
                child: Text('SAVE TOLL DETAILS', style: GoogleFonts.poppins(fontWeight: FontWeight.bold, color: Colors.white)),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Future<void> _pickImage() async {
    final XFile? file = await ImagePicker().pickImage(source: ImageSource.gallery, imageQuality: 85);
    if (file != null) {
      final bytes = await file.readAsBytes();
      setState(() {
        _imageFiles.add(bytes);
        _imageNames.add(file.name);
      });
    }
  }

  Widget _buildInputField({
    required TextEditingController controller,
    required String label,
    required String hint,
    TextInputType keyboardType = TextInputType.text,
    String? Function(String?)? validator,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label.toUpperCase(),
          style: GoogleFonts.poppins(
            fontSize: 10.5,
            fontWeight: FontWeight.bold,
            color: AppColors.secondaryText,
          ),
        ),
        const SizedBox(height: 4),
        TextFormField(
          controller: controller,
          keyboardType: keyboardType,
          validator: validator,
          style: GoogleFonts.poppins(fontSize: 13, fontWeight: FontWeight.bold, color: AppColors.primaryText),
          decoration: InputDecoration(
            hintText: hint,
            hintStyle: GoogleFonts.poppins(fontSize: 13, color: AppColors.secondaryText),
            isDense: true,
            contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
            filled: true,
            fillColor: Colors.white,
            enabledBorder: OutlineInputBorder(borderSide: const BorderSide(color: AppColors.divider)),
            focusedBorder: OutlineInputBorder(borderSide: const BorderSide(color: AppColors.secondary)),
          ),
        ),
      ],
    );
  }
}

// ----------------------------------------------------
// 4. Weighbridge Entry Sub Screen Form
// ----------------------------------------------------
class WeighbridgeEntryScreen extends StatefulWidget {
  final Map<String, dynamic>? initialData;
  const WeighbridgeEntryScreen({super.key, this.initialData});

  @override
  State<WeighbridgeEntryScreen> createState() => _WeighbridgeEntryScreenState();
}

class _WeighbridgeEntryScreenState extends State<WeighbridgeEntryScreen> {
  final _formKey = GlobalKey<FormState>();
  final _grossController = TextEditingController();
  final _tareController = TextEditingController();
  final _netController = TextEditingController();
  final _locationController = TextEditingController();
  final _dateTimeController = TextEditingController();
  dynamic _imageBytes;
  String? _imageName;

  @override
  void initState() {
    super.initState();
    _dateTimeController.text = DateTime.now().toString().split('.')[0];
    _grossController.addListener(_updateNetWeight);
    _tareController.addListener(_updateNetWeight);

    if (widget.initialData != null) {
      _grossController.text = widget.initialData!['grossWeight']?.toString() ?? '';
      _tareController.text = widget.initialData!['tareWeight']?.toString() ?? '';
      _netController.text = widget.initialData!['netWeight']?.toString() ?? '';
      _locationController.text = widget.initialData!['location'] ?? '';
      _dateTimeController.text = widget.initialData!['dateTime'] ?? '';
      _imageBytes = widget.initialData!['imageFile'];
      _imageName = widget.initialData!['imageName'];
    }
  }

  void _updateNetWeight() {
    final gross = double.tryParse(_grossController.text) ?? 0.0;
    final tare = double.tryParse(_tareController.text) ?? 0.0;
    final net = gross - tare;
    if (net >= 0) {
      _netController.text = net.toStringAsFixed(1);
    } else {
      _netController.text = '0.0';
    }
  }

  @override
  void dispose() {
    _grossController.removeListener(_updateNetWeight);
    _tareController.removeListener(_updateNetWeight);
    _grossController.dispose();
    _tareController.dispose();
    _netController.dispose();
    _locationController.dispose();
    _dateTimeController.dispose();
    super.dispose();
  }

  Future<void> _pickImage() async {
    final XFile? file = await ImagePicker().pickImage(source: ImageSource.gallery, imageQuality: 85);
    if (file != null) {
      final bytes = await file.readAsBytes();
      setState(() {
        _imageBytes = bytes;
        _imageName = file.name;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final isDesktop = MediaQuery.of(context).size.width > 768;

    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: CustomAppBar(
        centerTitle: false,
        title: Text(
          'Weighbridge Entry',
          style: Theme.of(context).textTheme.titleLarge?.copyWith(
            color: AppColors.background,
            fontWeight: FontWeight.bold,
          ),
        ),
      ),
      body: Form(
        key: _formKey,
        child: SingleChildScrollView(
          padding: EdgeInsets.symmetric(
            horizontal: isDesktop ? MediaQuery.of(context).size.width * 0.2 : 16.0,
            vertical: 16.0,
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              _buildInputField(
                controller: _locationController,
                label: 'Weighbridge Name / Location',
                hint: 'e.g. Highway Weigh Station',
                validator: (val) => val == null || val.trim().isEmpty ? 'Weighbridge Name is required' : null,
              ),
              const SizedBox(height: 12),
              Row(
                children: [
                  Expanded(
                    child: _buildInputField(
                      controller: _grossController,
                      label: 'Gross Weight (kg)',
                      hint: 'e.g. 25000',
                      keyboardType: const TextInputType.numberWithOptions(decimal: true),
                      validator: (val) {
                        if (val == null || val.trim().isEmpty) return 'Required';
                        if (double.tryParse(val) == null || double.parse(val) <= 0) return 'Invalid';
                        return null;
                      },
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: _buildInputField(
                      controller: _tareController,
                      label: 'Tare Weight (kg)',
                      hint: 'e.g. 10000',
                      keyboardType: const TextInputType.numberWithOptions(decimal: true),
                      validator: (val) {
                        if (val == null || val.trim().isEmpty) return 'Required';
                        if (double.tryParse(val) == null || double.parse(val) < 0) return 'Invalid';
                        return null;
                      },
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 12),
              Row(
                children: [
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'NET WEIGHT (kg)'.toUpperCase(),
                          style: GoogleFonts.poppins(
                            fontSize: 10.5,
                            fontWeight: FontWeight.bold,
                            color: AppColors.secondaryText,
                          ),
                        ),
                        const SizedBox(height: 4),
                        TextFormField(
                          controller: _netController,
                          readOnly: true,
                          style: GoogleFonts.poppins(
                            fontSize: 13,
                            fontWeight: FontWeight.bold,
                            color: AppColors.primaryText.withValues(alpha: 0.6),
                          ),
                          decoration: InputDecoration(
                            isDense: true,
                            contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
                            filled: true,
                            fillColor: Colors.grey.shade100,
                            enabledBorder: OutlineInputBorder(borderSide: const BorderSide(color: AppColors.divider)),
                            focusedBorder: OutlineInputBorder(borderSide: const BorderSide(color: AppColors.divider)),
                          ),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: _buildInputField(
                      controller: _dateTimeController,
                      label: 'Weigh Date/Time',
                      hint: 'YYYY-MM-DD HH:MM',
                      validator: (val) => val == null || val.trim().isEmpty ? 'Date is required' : null,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 20),
              Text(
                'SLIP ATTACHMENT',
                style: GoogleFonts.poppins(
                  fontSize: 10.5,
                  fontWeight: FontWeight.bold,
                  color: AppColors.secondaryText,
                ),
              ),
              const SizedBox(height: 8),
              _imageBytes == null
                  ? InkWell(
                      onTap: _pickImage,
                      child: Container(
                        height: 120,
                        decoration: BoxDecoration(
                          border: Border.all(color: AppColors.divider),
                          borderRadius: BorderRadius.circular(AppRadius.md),
                          color: Colors.grey.shade50,
                        ),
                        child: Center(
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              const Icon(Icons.add_photo_alternate_outlined, color: AppColors.secondary, size: 28),
                              const SizedBox(height: 6),
                              Text('Tap to upload weighbridge slip', style: GoogleFonts.nunito(fontSize: 12, color: AppColors.secondaryText)),
                            ],
                          ),
                        ),
                      ),
                    )
                  : Container(
                      height: 120,
                      decoration: BoxDecoration(
                        border: Border.all(color: AppColors.divider),
                        borderRadius: BorderRadius.circular(AppRadius.md),
                      ),
                      padding: const EdgeInsets.all(8),
                      child: Row(
                        children: [
                          const Icon(Icons.description_outlined, color: Colors.purple, size: 36),
                          const SizedBox(width: 12),
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                Text(
                                  _imageName ?? 'weighbridge_slip.jpg',
                                  style: GoogleFonts.poppins(fontSize: 13, fontWeight: FontWeight.bold, color: AppColors.primaryText),
                                  maxLines: 1,
                                  overflow: TextOverflow.ellipsis,
                                ),
                                const SizedBox(height: 4),
                                Text('Attached successfully', style: GoogleFonts.nunito(fontSize: 11, color: AppColors.success)),
                              ],
                            ),
                          ),
                          IconButton(
                            icon: const Icon(Icons.delete_outline, color: AppColors.error),
                            onPressed: () {
                              setState(() {
                                _imageBytes = null;
                                _imageName = null;
                              });
                            },
                          ),
                        ],
                      ),
                    ),
              const SizedBox(height: 32),
              ElevatedButton(
                onPressed: () {
                  if (_formKey.currentState!.validate()) {
                    if (_imageBytes == null) {
                      ScaffoldMessenger.of(context).showSnackBar(
                        const SnackBar(
                          content: Text('⚠️ Weighbridge slip attachment is required.'),
                          backgroundColor: AppColors.error,
                        ),
                      );
                      return;
                    }
                    Navigator.pop(context, {
                      'grossWeight': double.tryParse(_grossController.text) ?? 0.0,
                      'tareWeight': double.tryParse(_tareController.text) ?? 0.0,
                      'netWeight': double.tryParse(_netController.text) ?? 0.0,
                      'location': _locationController.text.trim(),
                      'dateTime': _dateTimeController.text.trim(),
                      'imageFile': _imageBytes,
                      'imageName': _imageName,
                    });
                  }
                },
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppColors.primary,
                  minimumSize: const Size(double.infinity, 48),
                ),
                child: Text('SAVE WEIGHBRIDGE ENTRY', style: GoogleFonts.poppins(fontWeight: FontWeight.bold, color: Colors.white)),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildInputField({
    required TextEditingController controller,
    required String label,
    required String hint,
    TextInputType keyboardType = TextInputType.text,
    String? Function(String?)? validator,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label.toUpperCase(),
          style: GoogleFonts.poppins(
            fontSize: 10.5,
            fontWeight: FontWeight.bold,
            color: AppColors.secondaryText,
          ),
        ),
        const SizedBox(height: 4),
        TextFormField(
          controller: controller,
          keyboardType: keyboardType,
          validator: validator,
          style: GoogleFonts.poppins(fontSize: 13, fontWeight: FontWeight.bold, color: AppColors.primaryText),
          decoration: InputDecoration(
            hintText: hint,
            hintStyle: GoogleFonts.poppins(fontSize: 13, color: AppColors.secondaryText),
            isDense: true,
            contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
            filled: true,
            fillColor: Colors.white,
            enabledBorder: OutlineInputBorder(borderSide: const BorderSide(color: AppColors.divider)),
            focusedBorder: OutlineInputBorder(borderSide: const BorderSide(color: AppColors.secondary)),
          ),
        ),
      ],
    );
  }
}
