// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkF48hpNU1TFaN3hKjSluy1-s0cc2fcGQ',
    appId: '1:475613162648:web:f29fc5a6446152ec7374ed',
    messagingSenderId: '475613162648',
    projectId: 'fleet-management-system-37a81',
    authDomain: 'fleet-management-system-37a81.firebaseapp.com',
    storageBucket: 'fleet-management-system-37a81.firebasestorage.app',
    measurementId: 'G-KS4TH9FC5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8KlQt_dT_UUCo2XbrmIxd7HuiMkLdo0Q',
    appId: '1:475613162648:android:512e3325007dff817374ed',
    messagingSenderId: '475613162648',
    projectId: 'fleet-management-system-37a81',
    storageBucket: 'fleet-management-system-37a81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdP7SuVrTLecV1si2QUCF5OVQr6AU668o',
    appId: '1:475613162648:ios:a2a708aeb92a16357374ed',
    messagingSenderId: '475613162648',
    projectId: 'fleet-management-system-37a81',
    storageBucket: 'fleet-management-system-37a81.firebasestorage.app',
    iosBundleId: 'com.fleetmanagement.driverMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdP7SuVrTLecV1si2QUCF5OVQr6AU668o',
    appId: '1:475613162648:ios:a2a708aeb92a16357374ed',
    messagingSenderId: '475613162648',
    projectId: 'fleet-management-system-37a81',
    storageBucket: 'fleet-management-system-37a81.firebasestorage.app',
    iosBundleId: 'com.fleetmanagement.driverMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkF48hpNU1TFaN3hKjSluy1-s0cc2fcGQ',
    appId: '1:475613162648:web:108d7893f59126567374ed',
    messagingSenderId: '475613162648',
    projectId: 'fleet-management-system-37a81',
    authDomain: 'fleet-management-system-37a81.firebaseapp.com',
    storageBucket: 'fleet-management-system-37a81.firebasestorage.app',
    measurementId: 'G-N75895X4P4',
  );
}
